apiVersion: v1
kind: Service
metadata:
  name: titan-control-plane
  namespace: titan
spec:
  selector:
    app: titan-control-plane

  ports:
    - name: http
      port: 8080
      targetPort: 8080

  type: ClusterIP
